name: mohammad_shakeri_file_manager
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  disk_space: ^0.2.1
  file_manager: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  path_provider: ^2.0.14
  percent_indicator: ^4.2.3
  permission_handler: ^10.2.0
  sizer: ^2.0.15
  storage_info: ^0.0.1
  photo_view: ^0.14.0
  flutter_pdfview: ^1.0.0
  video_player: ^2.1.10
  just_audio: ^0.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/3d/
  fonts:
      - family: IranYekan
        fonts:
          - asset: assets/fonts/IranYekan.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true